title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: sighingnow/jekyll-gitbook
title: [Saints Wiki]
description: [Insert Description Here]
plugins:
- jekyll-remote-theme #
- jemoji
#source: wiki/


## Sidebar

---
  defaults:
   #  _docs
    - scope:
        path: ""
        type: docs
      values:
        sidebar:
          nav: "docs"
  ---    